project: 
  type: website
  
execute:
  freeze: auto
  message: false

website: 
  page-navigation: true
  title: "Biostatistics Class Slides" 
  description: "Slides and other class material produced or compiled for biostatistics courses at Baruch and the CUNY Graduate Center"
  site-url: "https://jsgosnell.github.io/cuny_biostats_website/" 
  repo-url: "https://github.com/jsgosnell/cuny_biostats_website"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    center: "[Course notes](https://jsgosnell.github.io/cuny_biostats_book/) & [slides](https://jsgosnell.github.io/cuny_biostats_website/)"
    left: "[&copy; CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en) unless otherwise noted"  
  
  sidebar:
    background: "#D9E3E4"
    logo: images/platypus_from_1893_mivart.jpg
    title: "Biostats: Class material" 
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.gosnelllab.com/
        text: "Gosnell lab website"
      - icon: github
        href: https://github.com/jsgosnell
        text: "J. Stephen Gosnell github"
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Home
      - section: "Lessons"
        contents:
          - href: lessons/welcome_and_introduction.qmd
            text: Welcome and introduction
          - href: lessons/tools.qmd
            text: Introducing R, Rstudio, git, and markdown
          - href: lessons/estimation_and_probability.qmd
            text: Estimation and Probability
          - href: lessons/intro_to_hypothesis_testing_via_binomial.qmd
            text: Introducing hypothesis testing via the binomial distribution
          - href: lessons/intro_to_normality_via_one_sample_tests.qmd
            text: Introduction to normality and one-sample tests
          - href: lessons/contingency_analysis.qmd
            text: Compare proportions among groups
          - href: lessons/compare_means_among_groups.qmd
            text: Compare means among groups
          - href: lessons/More_ANOVAs.qmd
            text: More ANOVAs
            
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true



filters:
  - include-files.lua
  - quarto

  
