---
title: Estimation and probability
subtitle: Using a sample to make a guess and a guess about your guess
bibliography: ../references.bib
---

<!-- COMMENT NOT SHOW IN ANY OUTPUT: Code chunk below sets overall defaults for .qmd file; these inlcude showing output by default and looking for files relative to .Rpoj file, not .qmd file, which makes putting filesin different folders easier  -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Objective

To introduce students to how data can be used to estimate parameters of
interest and associated sampling error. Basic probability is also
reviewed, and students are introduced to the ggplot2 package in R. By
the end of the lesson, you should be able to

-   explain how sampling error is estimated (conceptually and via
    formulas) for various distributiond

-   develop and interpret 95% confidence intervals

-   Explain probability concepts including independence and
    conditionality and explain connections to the addition rule,
    multiplication rule

-   Explain the terms sensitivity and specificity

-   develop plots using ggplot2

## Background reading

Course notes links for background reading also contain code used to
produce R output used in slides.

-   [https://jsgosnell.github.io/cuny_biostats_book/content/chapters/Estimation.html](https://jsgosnell.github.io/cuny_biostats_book/content/chapters/Estimation.html){target="_blank"}

-   [https://jsgosnell.github.io/cuny_biostats_book/content/chapters/Probability.html](https://jsgosnell.github.io/cuny_biostats_book/content/chapters/Probability.html){target="_blank"}

## [Lecture slides (click to open in Google slides!)](https://docs.google.com/presentation/d/1wtBVeCfy14k8xPH0fw8R70b_PCrGSY971I5wJm0Q79E/edit?usp=sharing){target="_blank"}

```{=html}
<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTZFc0aa0dWVZWgpCfY2B494NXYAjDpyvEOgKZx7BVc86trUnaFv893C6QJGuRCMWN6mCUueTzZP38u/embed?start=false&loop=false&delayms=60000" frameborder="0" width="640" height="389" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
```
## [Connected assignment(click here)](https://jsgosnell.github.io/cuny_biostats_book/content/practice_problems/2_Estimates_and_ggplot2.html){target="_blank"}

Using these skills and applying concepts correctly to interpret data
sets may seem easy when you read about them or listen during class, but
practice is key to ensuring you understand the material. Practice
problems are provided for each lesson. The link above points you to the
appropriate link in the [course
notes](https://jsgosnell.github.io/cuny_biostats_book/){target="_blank"}.
You can make a copy (technically a *fork*, since you can't directly edit
it) of the entire course notes website in github \@
[https://github.com/jsgosnell/cuny_biostats_book](https://github.com/jsgosnell/cuny_biostats_book){target="_blank"}
and work from there. The benefit is this allows you to see updates to
the site (if you sync your fork). The downside is you have to work
interactively or build the entire site when you render a changed file.
This is doable but may take more time than students need (and may lead to merge issues!). 

Alternatively,your instructor may use a different
delivery method (like github classroom) or provide alternative problems.

**In general you should only work edit .qmd files! Everything/anything
else is produced during the session and should not be edited. All files
can be uploaded to github though.**

Solutions are also provided for all problems via the [course
notes](https://jsgosnell.github.io/cuny_biostats_book/){target="_blank"},
but try them before you look at the answers!

## Extra material

-   [Maintaining Standards: Differences between the Standard Deviation
    and Standard Error, and When to Use
    Each](http://journals.sagepub.com/doi/abs/10.1177/070674379604100805){target="_blank"}
    -   a helpful journal article
-   Tutorials produced by a group at UBC tha help visualize sampling,
    confidence intervals, and the central limit theorm
    -   [Sampling from a normally distributed
        population](https://www.zoology.ubc.ca/~whitlock/Kingfisher/SamplingNormal.htm){target="_blank"}
    -   [Confidence intervals for the
        mean](https://www.zoology.ubc.ca/~whitlock/Kingfisher/CIMean.htm){target="_blank"}
    -   [Sampling from a non-Normally distributed population (the
        central limit
        theorem)](https://www.zoology.ubc.ca/~whitlock/Kingfisher/CLT.htm){target="_blank"}
