---
title: Extending linear models
subtitle: When to trust it, and how to fix it when it's broken
bibliography: ../references.bib
---

<!-- COMMENT NOT SHOW IN ANY OUTPUT: Code chunk below sets overall defaults for .qmd file; these inlcude showing output by default and looking for files relative to .Rpoj file, not .qmd file, which makes putting filesin different folders easier  -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Objective

Here we will consider the robustness of linear models to broken
assumption. We will also extend the model to account for assumptions.
This module should be seen as a *brief* introduction to other
techniques; many of these approaches could be the focus of upper-level
classes.

By the end of the lesson, students should be able to

-   explain when linear models can be used despite broken assumptions
-   extend linear models using
    -   data transformations
    -   generalized linear models
    -   non-linear models
    -   random effects
    -   weighted least squares

## Background reading

Course notes links for background reading also contain code used to
produce R output used in slides.

-   [https://jsgosnell.github.io/cuny_biostats_book/content/chapters/Linear_model_extensions.html](https://jsgosnell.github.io/cuny_biostats_book/content/chapters/Linear_model_extensions.html){target="_blank"}

## [Lecture slides (click to open in Google slides!)](https://docs.google.com/presentation/d/1rngl7n5qE83Ks-PVAUlmVJ921qBiRTq64RhyZMMeBl4/edit?usp=sharing){target="_blank"}


```{=html}
<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTywtUOIRUnFv82UjliYr-k_bPydfvYNnEk-8QQ25NNlLJ-S8jo2R6_ENhMopQSII-QSShaoklhwx15/embed?start=false&loop=false&delayms=60000" frameborder="0" width="640" height="389" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
```

## [Connected assignment(click here)](https://jsgosnell.github.io/cuny_biostats_book/content/practice_problems/10_Linear_model_extensions.html){target="_blank"}

Using these skills and applying concepts correctly to interpret data
sets may seem easy when you read about them or listen during class, but
practice is key to ensuring you understand the material. Practice
problems are provided for each lesson. The link above points you to the
appropriate link in the [course
notes](https://jsgosnell.github.io/cuny_biostats_book/){target="_blank"}.
You can make a copy (technically a *fork*, since you can't directly edit
it) of the entire course notes website in github \@
[https://github.com/jsgosnell/cuny_biostats_book](https://github.com/jsgosnell/cuny_biostats_book){target="_blank"}
and work from there. The benefit is this allows you to see updates to
the site (if you sync your fork). The downside is you have to work
interactively or build the entire site when you render a changed file.
This is doable but may take more time than students need (and may lead
to merge issues!).

Alternatively,your instructor may use a different delivery method (like
github classroom) or provide alternative problems.

**In general you should only work edit .qmd files! Everything/anything
else is produced during the session and should not be edited. All files
can be uploaded to github though.**

Solutions are also provided for all problems via the [course
notes](https://jsgosnell.github.io/cuny_biostats_book/){target="_blank"},
but try them before you look at the answers!

## Extra material

## Data referenced in class
